import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/navbar/Navbar';
import AuthProvider from '@/supabase/Provider';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import 'react-quill/dist/quill.snow.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Dev Medium',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: ReactNode;
}) {
    const supabase = createServerComponentClient({ cookies });

    const {
        data: { session },
    } = await supabase.auth.getSession();

    const {
        data: { user },
    } = await supabase.auth.getUser();

    return (
        <html lang='en'>
            <body className={inter.className}>
                <Navbar />
                <AuthProvider
                    accessToken={session?.access_token as unknown as string}
                >
                    {children}
                </AuthProvider>
            </body>
        </html>
    );
}
